// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/tokenValidator.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Token struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9444bdd25faed23, []int{0}
}

func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (m *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(m, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type ValidatedToken struct {
	StatusCode           int32    `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	UserRole             string   `protobuf:"bytes,3,opt,name=userRole,proto3" json:"userRole,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidatedToken) Reset()         { *m = ValidatedToken{} }
func (m *ValidatedToken) String() string { return proto.CompactTextString(m) }
func (*ValidatedToken) ProtoMessage()    {}
func (*ValidatedToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9444bdd25faed23, []int{1}
}

func (m *ValidatedToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidatedToken.Unmarshal(m, b)
}
func (m *ValidatedToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidatedToken.Marshal(b, m, deterministic)
}
func (m *ValidatedToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidatedToken.Merge(m, src)
}
func (m *ValidatedToken) XXX_Size() int {
	return xxx_messageInfo_ValidatedToken.Size(m)
}
func (m *ValidatedToken) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidatedToken.DiscardUnknown(m)
}

var xxx_messageInfo_ValidatedToken proto.InternalMessageInfo

func (m *ValidatedToken) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *ValidatedToken) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *ValidatedToken) GetUserRole() string {
	if m != nil {
		return m.UserRole
	}
	return ""
}

func init() {
	proto.RegisterType((*Token)(nil), "proto.Token")
	proto.RegisterType((*ValidatedToken)(nil), "proto.ValidatedToken")
}

func init() { proto.RegisterFile("proto/tokenValidator.proto", fileDescriptor_e9444bdd25faed23) }

var fileDescriptor_e9444bdd25faed23 = []byte{
	// 234 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8e, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0xad, 0x92, 0x52, 0x07, 0xe9, 0x61, 0x51, 0x09, 0x01, 0x45, 0x72, 0xf2, 0xd2, 0xac,
	0xad, 0x4f, 0xa0, 0x2d, 0x6a, 0xaf, 0x31, 0x78, 0xf0, 0x22, 0xdb, 0xec, 0xd0, 0x2e, 0xc6, 0x4c,
	0x98, 0xec, 0xf6, 0xf9, 0xa5, 0x93, 0x28, 0xcd, 0x69, 0xf6, 0x9b, 0xf9, 0x76, 0xe6, 0x87, 0xa4,
	0x61, 0xf2, 0xa4, 0x3d, 0x7d, 0x63, 0xfd, 0x61, 0x2a, 0x67, 0x8d, 0x27, 0xce, 0xa4, 0xa9, 0x22,
	0x29, 0xe9, 0x0d, 0x44, 0xc5, 0x61, 0xac, 0x2e, 0x21, 0x12, 0x2f, 0x1e, 0xdd, 0x8d, 0xee, 0xcf,
	0xf3, 0x0e, 0x52, 0x0b, 0xd3, 0xfe, 0x23, 0xda, 0xce, 0xbb, 0x05, 0x68, 0xbd, 0xf1, 0xa1, 0x5d,
	0x92, 0x45, 0x91, 0xa3, 0xfc, 0xa8, 0xa3, 0xae, 0x61, 0x1c, 0x5a, 0xe4, 0xb5, 0x8d, 0x4f, 0x65,
	0x51, 0x4f, 0x2a, 0x81, 0xc9, 0xe1, 0x95, 0x53, 0x85, 0xf1, 0x99, 0x4c, 0xfe, 0x79, 0xb1, 0x84,
	0x69, 0x31, 0xc8, 0xa8, 0xe6, 0x30, 0xf9, 0xbb, 0xab, 0x2e, 0xba, 0xc4, 0x99, 0x28, 0xc9, 0x55,
	0x4f, 0xc3, 0x58, 0xe9, 0xc9, 0xf3, 0xdb, 0xe7, 0xcb, 0xd6, 0xf9, 0x5d, 0xd8, 0x64, 0x25, 0xfd,
	0xe8, 0x75, 0xf1, 0x34, 0x5b, 0xd5, 0xae, 0x61, 0xd2, 0xab, 0x66, 0xb6, 0x98, 0x3f, 0x7c, 0xbd,
	0x92, 0x36, 0xc1, 0xef, 0xde, 0x91, 0xf7, 0xae, 0x44, 0xed, 0x6a, 0x8f, 0x5c, 0x9b, 0x4a, 0xb7,
	0xc8, 0x7b, 0x64, 0xbd, 0xe5, 0xa6, 0xd4, 0xb2, 0x7a, 0x33, 0x96, 0xf2, 0xf8, 0x1b, 0x00, 0x00,
	0xff, 0xff, 0xfe, 0x33, 0x94, 0xca, 0x3f, 0x01, 0x00, 0x00,
}
