// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TokenValidatorClient is the client API for TokenValidator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TokenValidatorClient interface {
	Validate(ctx context.Context, in *Token, opts ...grpc.CallOption) (*ValidatedToken, error)
}

type tokenValidatorClient struct {
	cc grpc.ClientConnInterface
}

func NewTokenValidatorClient(cc grpc.ClientConnInterface) TokenValidatorClient {
	return &tokenValidatorClient{cc}
}

func (c *tokenValidatorClient) Validate(ctx context.Context, in *Token, opts ...grpc.CallOption) (*ValidatedToken, error) {
	out := new(ValidatedToken)
	err := c.cc.Invoke(ctx, "/proto.TokenValidator/Validate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TokenValidatorServer is the server API for TokenValidator service.
// All implementations must embed UnimplementedTokenValidatorServer
// for forward compatibility
type TokenValidatorServer interface {
	Validate(context.Context, *Token) (*ValidatedToken, error)
	mustEmbedUnimplementedTokenValidatorServer()
}

// UnimplementedTokenValidatorServer must be embedded to have forward compatible implementations.
type UnimplementedTokenValidatorServer struct {
}

func (UnimplementedTokenValidatorServer) Validate(context.Context, *Token) (*ValidatedToken, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Validate not implemented")
}
func (UnimplementedTokenValidatorServer) mustEmbedUnimplementedTokenValidatorServer() {}

// UnsafeTokenValidatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TokenValidatorServer will
// result in compilation errors.
type UnsafeTokenValidatorServer interface {
	mustEmbedUnimplementedTokenValidatorServer()
}

func RegisterTokenValidatorServer(s grpc.ServiceRegistrar, srv TokenValidatorServer) {
	s.RegisterService(&TokenValidator_ServiceDesc, srv)
}

func _TokenValidator_Validate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Token)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenValidatorServer).Validate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TokenValidator/Validate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenValidatorServer).Validate(ctx, req.(*Token))
	}
	return interceptor(ctx, in, info, handler)
}

// TokenValidator_ServiceDesc is the grpc.ServiceDesc for TokenValidator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TokenValidator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.TokenValidator",
	HandlerType: (*TokenValidatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Validate",
			Handler:    _TokenValidator_Validate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/tokenValidator.proto",
}
